---
- name: provision
  hosts: localhost
  become: yes

  vars:
    USER: ""
    EMAIL: ""
    HOME: "/home/{{USER}}"

  roles:
    - account
    - packages
    - firewall

  post_tasks:
    - name: "Print public key"
      debug:
        var: public_key