---
# - include_tasks: upgrade.yml
- include_tasks: python.yml
- include_tasks: tools.yml
- include_tasks: emacs.yml
- include_tasks: docker.yml

- include_tasks: add_key_repo_package.yml
  loop: "{{package_configs}}"
  loop_control:
    loop_var: package_config


