---
- name: "Install tools from apt"
  apt:
    name:
      - gnome-tweak-tool
      - gnome-shell-extensions
      - chrome-gnome-shell
      - dconf-cli
      - curl
      - htop
      - httpie
      - nmap
      - tree
      - vim
