---
- name: "Generate ssh key pair"
  user:
    name: "{{USER}}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{EMAIL}}"
  register: user_result

- name: "Store public key"
  set_fact:
    public_key: "{{user_result.ssh_public_key}}"

- name: "Add bash aliases"
  blockinfile:
    dest: "/home/{{USER}}/.bashrc"
    block: |
      alias ll='ls -ls'
      alias la='ls -lsa'
      alias psgrep='ps aux | grep'
      alias tree='tree --dirsfirst -F'
      
      # Emacs in terminal
      alias emcli='emacs -nw'
      
      # Docker
      alias dormac='docker container rm $(docker container ls -aq)'
      alias dormai='docker image rm $(docker image ls -aq)'
      
      # OpenSSL
      alias csr='openssl req -verify -text -noout -in'
      alias cert='openssl x509 -text -noout -in'

- name: "Configure git"
  template:
    src: gitconfig.j2
    dest: "{{HOME}}/.gitconfig"
    owner: "{{USER}}"
    group: "{{USER}}"
    mode: "664"

